apiVersion: v1
kind: Service
metadata: 
  labels: 
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Grafana"
  name: monitoring-grafana
spec: 
  ports: 
    - port: 80
      targetPort: 8080
  selector: 
    name: influxGrafana

