apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    name: heapster
    kubernetes.io/cluster-service: "true"
  name: monitoring-heapster-controller
spec: 
  replicas: 1
  selector: 
    name: heapster
  template: 
    metadata: 
      labels: 
        name: heapster
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: gcr.io/google_containers/heapster:v0.12.1
          name: heapster
          command:
            - /heapster
            - --source=kubernetes:http://kubernetes?auth=
            - --sink=influxdb:http://monitoring-influxdb:8086
